### ISSUE TITLE
windows系统下编译请教

### ISSUE THREAD

**Issue by mhtt** [imaben/php-beast-binaries#1]
你好！
我由于是通过WampServer搭建的web环境，是线程安全的，所以需要编译php-beast ts版本的dll，我尝试了多种方法都编译失败，请问能否说明下大概的编译流程，或者能否在http://blog.csdn.net/mycwq/article/details/10165955 这个基础上做相应的修改实现编译。
谢谢！！！

**Comment by imaben** [comment]
TS版本不是没有编译，而是扩展本身现在还没有做支持，后续版本会支持！
