### ISSUE TITLE
本人菜鸟，所以请问windows版beast怎样配置和使用

### ISSUE THREAD

**Issue by zhangunj** [imaben/php-beast-binaries#2]
您好，本人菜鸟，所以请问：
1、windows版beast怎样配置和使用
2、是否可以像linux版本（php-beast）那样修改加密的key、加密后的头文件结构、添加本机的物理网卡地址等，如果可以，怎样操作。
3、php7为什么没有VC11编译版
4、谢谢。

**Comment by imaben** [comment]
1、如果没有定制化需求，直接下载dll，放在extension_dir下，extension=xxx.dll，加载上即可使用。
2、想定制化，只能自己编译，编译教程见：https://wiki.php.net/internals/windows/stepbystepbuild
3、因为php7原生就是vc14编译出来的。
4、不客气。

**Comment by zhangunj** [comment]
谢谢，
看来还要继续研究鸟文了

**Comment by zhangunj** [comment]
@imaben 
谢谢，
看来还要继续研究鸟文了
