### ISSUE TITLE
windwos编译错误

### ISSUE THREAD

**Issue by shuyabin** [imaben/php-beast-binaries#3]
大神你好,我在windwos编译出错了..求大神指导一下.谷歌也没找到答案..

![image](https://cloud.githubusercontent.com/assets/14884581/26792993/e61a06ae-4a4e-11e7-83c7-21236038292d.png)

之前出现了
 输入错误: 没有文件扩展“.js”的脚本引擎。
然后我吧
regedit 把 [HKEY_CLASSES_ROOT\.js] 项下的那个默认值改成JSFile

**Comment by imaben** [comment]
为啥要用cygwin？

**Comment by shuyabin** [comment]
那是我 从help 参数随便选的一个. 不管哪个参数都会显示 那个错误

**Comment by imaben** [comment]
你直接用的cmd吧，别用系统自带的cmd，用vs自带的，在开始->visual studio-> visual studio tools->VS2012 x64 Native Tools Command Prompt.exe，里面有好几个命令行工具，根据你自己的平台选择，打开后定位到对应的目录再执行configure

**Comment by shuyabin** [comment]
我是用vs的cmd . 但是我是64位系统, 编译x86 -  -有问题嘛?

**Comment by imaben** [comment]
没问题，看提示是找不到编译器。

**Comment by imaben** [comment]
我抽时间出个教程吧

**Comment by shuyabin** [comment]
好的.非常感谢. 但是现在卡不过去了..  找不到编译器 - - 怎么破.

**Comment by imaben** [comment]
你在那个群里吗？加我Q，我给你看一下吧

**Comment by shuyabin** [comment]
非常感谢,我现在在出差.等我到公司. 我在那个群里

**Comment by imaben** [comment]
嗯

**Comment by shuyabin** [comment]
@imaben  大腿,上次我用vs2017编译报错。我换成了vs2012编译报错

![image](https://user-images.githubusercontent.com/14884581/26908660-9a12a518-4c2e-11e7-85a0-5e2bc855dbad.png)

看网上说要运行vcvarsall.bat 但是我在vs的安装包里.都没有搜索到这个文件.
求大腿指导..

**Comment by imaben** [comment]
编译器不要乱用，你看官方这个版本用的哪个编译器你就用哪个就好了，混用的话dll加载容易出问题

**Comment by shuyabin** [comment]
![image](https://user-images.githubusercontent.com/14884581/26908915-39e76834-4c30-11e7-9348-8fb83d0ef545.png)

我现在装的就是vs2012的


但是官网要求的是x84的  但是我本机装好以后,就只有x64的..会ying影响这编译报错嘛...

**Comment by imaben** [comment]
你编译哪个版本的php？

**Comment by shuyabin** [comment]
5.6

**Comment by shuyabin** [comment]
@imaben  大腿,你好. 我这边编译其他的扩展都能成功。。为什么编译beast的时候就报错了.. 

![image](https://user-images.githubusercontent.com/14884581/27065154-373fcf7a-502e-11e7-83c5-1bb24fd83ab7.png)


![image](https://user-images.githubusercontent.com/14884581/27065108-07538810-502e-11e7-8514-7ed02aa802d0.png)

![image](https://user-images.githubusercontent.com/14884581/27065122-1853193c-502e-11e7-89ff-1c2e9fb10ba3.png)

**Comment by imaben** [comment]
没截对，截图再往上截

**Comment by shuyabin** [comment]
![image](https://user-images.githubusercontent.com/14884581/27065271-d2105600-502e-11e7-8a38-5a1cb3aed410.png)

**Comment by imaben** [comment]
这个其实是编译顺序有问题，你先找到php_globals.h，把出错的那一行先注释掉，编译到最后的时候会再报一个global undefined类似的错，到那时再把注释掉的那一行打开就可以编译通过了

**Comment by shuyabin** [comment]
.. 注释掉?然后开始编译.然后报错后再打开再重新编译一下嘛?

**Comment by imaben** [comment]
对，就按我上面 说的做就好了

**Comment by shuyabin** [comment]
我吧这行给注释了. 然后编译了然后又开启了.但是最后报错 也 nmake clean了
extern PHPAPI int core_globals_id;

![1](https://user-images.githubusercontent.com/14884581/27066238-3021667a-5035-11e7-887d-d3a6fac2d86c.png)



![2](https://user-images.githubusercontent.com/14884581/27066289-8e370c74-5035-11e7-8b60-27f26469d1c0.png)

**Comment by imaben** [comment]
这个报错是因为没有找到php5.lib，你看看Release目录下有没有那个文件

**Comment by shuyabin** [comment]
php5ts.lib, 只有一个ts的lib .我之前从其他地方复制了一份。。但是编译的时候一开始就报错.打不开这个文件..

**Comment by imaben** [comment]
你是不是要编译ts版？

**Comment by imaben** [comment]
你改一下源码，或把php5ts.lib重命名一下，这个地方我还没对ts版本做兼容

**Comment by imaben** [comment]
不要从其它地方复制，从其它地方复制的很有可能链接会有问题

**Comment by shuyabin** [comment]
非常感谢大腿的帮助.现在编译成功了.

**Comment by shuyabin** [comment]
编译成功了..但是加载的时候显示 不是有效的win32应用程序。是为啥?

**Comment by imaben** [comment]
你是不是用的ARM平台编译的？

**Comment by shuyabin** [comment]
…是在win7 64系统上编译的，电脑是mac  cpu 是i5 的一款

**Comment by shuyabin** [comment]
命令行就是vs2012  native tools的那个。
