### ISSUE TITLE
PHP7.1.15 x64 nts windows版本报错

### ISSUE THREAD

**Issue by Craft24** [imaben/php-beast-binaries#4]
windows版，iis10，PHP7.1.15 x64 nts报错，FastCGI意外退出，把extension去掉就不报这个错误

**Comment by imaben** [comment]
你试一下在命令行下正常吗？

**Comment by Craft24** [comment]
命令行下可以，我用phpinfo试的

**Comment by Craft24** [comment]
命令行下加密解密都正常

**Comment by Craft24** [comment]
IIS环境下FastCGI进程异常退出：尝试将IIS的运行用户从ApplicationPoolIdentity改为LocalSystem  
![applicationpoolidentity](https://user-images.githubusercontent.com/3214297/30731243-e0c3157e-9f9e-11e7-9e86-24e3efe692a7.png)
![localsystem](https://user-images.githubusercontent.com/3214297/30731245-e0f6de86-9f9e-11e7-9d24-df01e87c3445.png)
